### ISSUE TITLE
Cannot install package on Windows 7, Atom v. 0.106.0-88df4d2

### ISSUE THREAD

**Issue by ryanewtaylor** [lsegal/atom-rst-preview#7]
When I attempt to install the rst preview I receive the following error message.

    > runas@0.5.4 install C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher\node_modules\runas
    > node-gyp rebuild

    C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher\node_modules\runas>node "c:\Tools\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      main.cc
      runas_win.cc
         Creating library C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher\node_modules\runas\build\Release\runas.lib and object C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher\node_modules\runas\build\Release\runas.exp
      Generating code
      Finished generating code
      runas.vcxproj -> C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher\node_modules\runas\build\Release\\runas.node

    > pathwatcher@0.16.0 install C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher
    > node-gyp rebuild

    C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher>node "c:\Tools\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      main.cc
      handle_map.cc
      pathwatcher_win.cc
      common.cc
    ..\src\pathwatcher_win.cc(298): error C3861: 'CancelIoEx': identifier not found [C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed\node_modules\rst-preview\node_modules\pathwatcher\build\pathwatcher.vcxproj]

    npm http GET https://registry.npmjs.org/pathwatcher/0.16.0
    npm http GET https://registry.npmjs.org/underscore-plus
    npm http GET https://registry.npmjs.org/fs-plus
    npm http 304 https://registry.npmjs.org/underscore-plus
    npm http 304 https://registry.npmjs.org/fs-plus
    npm http 304 https://registry.npmjs.org/pathwatcher/0.16.0
    npm http GET https://registry.npmjs.org/q
    npm http GET https://registry.npmjs.org/nan/0.8.0
    npm http GET https://registry.npmjs.org/emissary
    npm http GET https://registry.npmjs.org/bindings
    npm http GET https://registry.npmjs.org/async
    npm http GET https://registry.npmjs.org/runas
    npm http GET https://registry.npmjs.org/underscore
    npm http GET https://registry.npmjs.org/rimraf
    npm http GET https://registry.npmjs.org/async
    npm http GET https://registry.npmjs.org/mkdirp
    npm http 304 https://registry.npmjs.org/q
    npm http 304 https://registry.npmjs.org/bindings
    npm http 304 https://registry.npmjs.org/async
    npm http 304 https://registry.npmjs.org/underscore
    npm http 304 https://registry.npmjs.org/runas
    npm http 304 https://registry.npmjs.org/emissary
    npm http 304 https://registry.npmjs.org/nan/0.8.0
    npm http 304 https://registry.npmjs.org/rimraf
    npm http 304 https://registry.npmjs.org/async
    npm http 304 https://registry.npmjs.org/mkdirp
    npm http GET https://registry.npmjs.org/mixto
    npm http GET https://registry.npmjs.org/property-accessors
    npm http 304 https://registry.npmjs.org/mixto
    npm http 304 https://registry.npmjs.org/property-accessors
    gypnpm ERR! pathwatcher@0.16.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the pathwatcher@0.16.0 install script.
    npm ERR! This is most likely a problem with the pathwatcher package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls pathwatcher
    npm ERR! There is likely additional logging output above.

    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "c:\\Tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\rtaylor\\.atom\\.apmrc" "install" "C:\\Users\\rtaylor\\.atom\\.node-gyp\\.atom\\.apm\\rst-preview\\1.0.2\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2012"
    npm ERR! cwd C:\Users\rtaylor\AppData\Local\Temp\apm-install-dir-11462-7684-1p4h8ed
    npm ERR! node -v v0.10.26
    npm ERR! npm -v 1.4.4
    npm ERR! code ELIFECYCLE
    npm

**Comment by lsegal** [comment]
Resolved with above commit
